/* SPDX-FileCopyrightText: 2023 Anoptic Game Engine Authors
 *
 * SPDX-License-Identifier: LGPL-3.0 */
/*  == Anoptic Game Engine v0.0000001 == */

/* Phase 6 step-1 gate: the determinism kernel is bit-compatible with CPython
 * 3.12 (TECH_SPEC §8). Every vector below was generated by the prototype's
 * interpreter (.venv python 3.12.6) — BLAKE2b-8 stream tags, MT19937 seeding
 * (including the magnitude-dependent key-word count), random(), randint,
 * choice, choices(weights), shuffle, uniform, sample, gauss, and Python 3
 * banker's rounding. Doubles compare EXACTLY (memcmp via ==): a 1-ULP drift
 * can flip a musical decision, so approximate equality would be a false gate.
 * Exit 0 == pass. */

#include <stdio.h>
#include <string.h>

#include "music/music_det.h"
#include "music/music_theory.h"

static int failures = 0;
#define CHECK(cond, msg) do { \
    if (!(cond)) { printf("FAIL: %s (%s:%d)\n", (msg), __FILE__, __LINE__); failures++; } \
} while (0)

static bool feq(double a, double b) { return a == b; }

int main(void)
{
    // --- BLAKE2b-8 tag -> big-endian seed ---
    {
        static const struct { const char *tag; uint64_t seed; } T[] = {
            { "42:harmony:0", 8787824866936948292ull },
            { "42:pad:3", 12519350287267456147ull },
            { "7:clock:1", 6121026043500429627ull },
            { "12345:signature", 200617767666870415ull },
        };
        for (size_t i = 0; i < sizeof T / sizeof T[0]; ++i) {
            uint8_t d[8];
            ano_music_blake2b8(T[i].tag, strlen(T[i].tag), d);
            uint64_t seed = 0;
            for (int b = 0; b < 8; ++b)
                seed = seed << 8 | d[b];
            CHECK(seed == T[i].seed, "blake2b8 tag digest");
        }
    }

    AnoMusicRng r;

    // --- MT19937 seeding: two-word key ---
    ano_music_rng_seed(&r, 0x123456789ABCDEF0ull);
    {
        static const uint32_t V[4] = { 3646699384u, 2523371432u, 4144361526u, 3901169663u };
        for (int i = 0; i < 4; ++i)
            CHECK(ano_music_getrandbits32(&r) == V[i], "getrandbits32 two-word seed");
    }
    ano_music_rng_seed(&r, 0x123456789ABCDEF0ull);
    {
        static const double V[4] = { 0.849063363578306, 0.9649343632780897,
                                     0.8861196598032612, 0.4675365935847732 };
        for (int i = 0; i < 4; ++i)
            CHECK(feq(ano_music_random(&r), V[i]), "random() two-word seed");
    }

    // --- one-word key (seed < 2^32 must NOT zero-pad to two words) ---
    ano_music_rng_seed(&r, 5);
    CHECK(feq(ano_music_random(&r), 0.6229016948897019), "random() small seed [0]");
    CHECK(feq(ano_music_random(&r), 0.7417869892607294), "random() small seed [1]");

    // --- randint (rejection sampling order) ---
    ano_music_rng_seed(&r, 0xDEADBEEFCAFEBABEull);
    {
        static const int64_t V[8] = { 2, 6, 6, 4, 5, 6, 5, 6 };
        for (int i = 0; i < 8; ++i)
            CHECK(ano_music_randint(&r, 0, 6) == V[i], "randint(0,6)");
    }

    // --- choice over 7 items (values 100..106) ---
    ano_music_rng_seed(&r, 0xDEADBEEFCAFEBABEull);
    {
        static const uint32_t V[6] = { 2, 6, 6, 4, 5, 6 };
        for (int i = 0; i < 6; ++i)
            CHECK(ano_music_choice(&r, 7) == V[i], "choice(7)");
    }

    // --- choices with float weights (cumulative-sum + bisect order) ---
    ano_music_rng_seed(&r, 99);
    {
        static const double w[4] = { 0.1, 2.5, 0.7, 1.3 };
        static const uint32_t V[6] = { 1, 1, 1, 1, 3, 1 }; // b b b b d b
        for (int i = 0; i < 6; ++i)
            CHECK(ano_music_choices1(&r, w, 4) == V[i], "choices(weights)");
    }

    // --- gauss (cached pair) ---
    ano_music_rng_seed(&r, 99);
    {
        static const double V[4] = { -0.5502226977406026, 0.3791183269784834,
                                     0.3269272865950446, 0.6813984972950928 };
        for (int i = 0; i < 4; ++i)
            CHECK(feq(ano_music_gauss(&r, 0.0, 1.0), V[i]), "gauss(0,1)");
    }

    // --- shuffle (reverse Fisher-Yates draw order) ---
    ano_music_rng_seed(&r, 99);
    {
        uint32_t idx[8] = { 0, 1, 2, 3, 4, 5, 6, 7 };
        static const uint32_t V[8] = { 7, 2, 0, 5, 4, 1, 3, 6 };
        ano_music_shuffle(&r, idx, 8);
        CHECK(memcmp(idx, V, sizeof V) == 0, "shuffle(8)");
    }

    // --- uniform ---
    ano_music_rng_seed(&r, 99);
    {
        static const double V[3] = { 0.11591229977466533, -0.6996982217002183,
                                     -0.7847907176535509 };
        for (int i = 0; i < 3; ++i)
            CHECK(feq(ano_music_uniform(&r, -1.5, 2.5), V[i]), "uniform(-1.5,2.5)");
    }

    // --- sample (pool method under the setsize heuristic) ---
    ano_music_rng_seed(&r, 99);
    {
        uint32_t out[5];
        static const uint32_t V[5] = { 12, 19, 6, 5, 7 };
        ano_music_sample(&r, 20, 5, out);
        CHECK(memcmp(out, V, sizeof V) == 0, "sample(20,5)");
    }

    // --- banker's rounding (decimal, ties to even) ---
    CHECK(feq(ano_music_round(0.125, 2), 0.12), "round(0.125, 2)");
    CHECK(feq(ano_music_round(0.135, 2), 0.14), "round(0.135, 2)");
    CHECK(feq(ano_music_round(2.675, 2), 2.67), "round(2.675, 2)");
    CHECK(feq(ano_music_round(96.4499999, 2), 96.45), "round(96.4499999, 2)");
    CHECK(feq(ano_music_round(1.0000000000499, 10), 1.0), "round(x, 10)");
    CHECK(feq(ano_music_round(0.0605, 3), 0.06), "round(0.0605, 3)");
    CHECK(feq(ano_music_round(-0.125, 2), -0.12), "round(-0.125, 2)");
    CHECK(ano_music_round_int(0.5) == 0, "round_int(0.5)");
    CHECK(ano_music_round_int(1.5) == 2, "round_int(1.5)");
    CHECK(ano_music_round_int(2.5) == 2, "round_int(2.5)");

    // --- interleaved mixed draws on one stream (word-consumption interactions:
    // rejection redraws, the two-word random(), the gauss pair cache) ---
    {
        AnoMusicRng m;
        ano_music_stream(&m, "42:mixgate:7");
        static const double w[5] = { 1.0, 0.25, 3.5, 0.01, 2.2 };
        static const double F[12] = {
            0.822429202845883, 0.5316778711285739, 0.6460546262643676,
            0.09639279084209407, 0.4743202896567267, -0.16764828566624135,
            0.8137117332096354, 1.6986907334101895, 0.16437814307286114,
            1.0615717307064352, 0.5146717787518651, -2.8842809783387984,
        };
        static const int64_t I[18] = { 10, 2, 2, -1, 6, 2, 3, 5, 0,
                                       3, 9, 4, 4, 12, 4, 1, 0, 2 };
        int fi = 0, ii = 0;
        for (int i = 0; i < 30; ++i) {
            switch (i % 5) {
            case 0: CHECK(feq(ano_music_random(&m), F[fi++]), "mixgate random"); break;
            case 1: CHECK(ano_music_randint(&m, -3, 11) == I[ii++], "mixgate randint"); break;
            case 2: CHECK(ano_music_choice(&m, 13) == (uint32_t)I[ii++], "mixgate choice"); break;
            case 3: CHECK(ano_music_choices1(&m, w, 5) == (uint32_t)I[ii++], "mixgate choices"); break;
            default: CHECK(feq(ano_music_gauss(&m, 0.5, 2.0), F[fi++]), "mixgate gauss"); break;
            }
        }
    }

    // --- stream doctrine: same tag twice = same first draw (§8.1a) ---
    {
        AnoMusicRng s1, s2;
        ano_music_stream(&s1, "42:clock:3");
        ano_music_stream(&s2, "42:clock:3");
        CHECK(feq(ano_music_random(&s1), ano_music_random(&s2)), "fresh stream per tag");
    }

    // ======================================================================
    // Theory kernel vs prototype vectors (same interpreter, same seeds)
    // ======================================================================

    // --- the functional walk: 24 scripted bars over fresh per-bar streams ---
    {
        // degree, extMask, inversion, sourceMode(-1 none), applied
        static const int8_t W[24][5] = {
            {1,0,0,-1,0},{6,0,0,-1,0},{4,0,0,-1,0},{5,0,0,-1,0},{3,0,0,-1,0},
            {5,0,0,-1,0},{5,1,0,-1,0},{1,0,0,-1,0},{2,0,0,-1,0},{5,0,0,-1,0},
            {6,0,0,-1,0},{5,0,0,-1,0},{3,0,0,-1,0},{5,1,0,-1,0},{1,1,0,-1,4},
            {5,1,0,-1,0},{1,0,0,-1,0},{4,1,0,5,0},{5,3,0,-1,0},{7,1,0,-1,0},
            {1,1,0,-1,0},{2,1,0,-1,0},{5,3,0,-1,0},{6,1,0,-1,0},
        };
        static const AnoMode MODE3[3] = { ANO_MODE_IONIAN, ANO_MODE_AEOLIAN,
                                          ANO_MODE_MIXOLYDIAN };
        AnoHarmonyConfig cfg = ano_harmony_config_default();
        AnoChord prev = ano_chord_none();
        for (int bar = 0; bar < 24; ++bar) {
            AnoCadenceSlot slot = bar % 8 == 7 ? ANO_SLOT_CADENCE
                                : bar % 8 == 6 ? ANO_SLOT_PRE_CADENCE
                                : bar % 8 == 0 ? ANO_SLOT_OPEN : ANO_SLOT_FREE;
            AnoCadencePolicy policy = (AnoCadencePolicy)(bar / 8);
            double tension = ano_music_round(0.05 + bar * 0.04, 10);
            double valence = ano_music_round(0.9 - bar * 0.08, 10);
            char tag[32];
            snprintf(tag, sizeof tag, "42:harmony:%d", bar);
            AnoMusicRng rng;
            ano_music_stream(&rng, tag);
            AnoChord c = ano_next_chord(prev, slot, policy, tension, valence,
                                        MODE3[bar % 3], bar % 8 == 0, bar == 0,
                                        &cfg, &rng, bar % 5 == 2,
                                        bar == 14 ? 4 : 0, bar == 22);
            bool ok = c.degree == W[bar][0] && c.extensions == W[bar][1]
                   && c.inversion == W[bar][2] && c.sourceMode == W[bar][3]
                   && c.applied == W[bar][4];
            if (!ok)
                printf("  walk bar %d: got %d %d %d %d %d\n", bar, c.degree,
                       c.extensions, c.inversion, c.sourceMode, c.applied);
            CHECK(ok, "harmony walk bar");
            prev = c;
        }
    }

    // --- voicing chain: exact voicings AND exact float costs ---
    {
        static const uint8_t PCS[5][5] = {
            { 0, 4, 7 }, { 5, 9, 0 }, { 7, 11, 2, 5 }, { 2, 5, 9, 0, 4 }, { 9, 0, 4 },
        };
        static const uint32_t PCN[5] = { 3, 3, 4, 5, 3 };
        static const int V[5][4] = {
            { 55, 64, 67, 72 }, { 53, 65, 69, 72 }, { 55, 65, 71, 74 },
            { 53, 64, 72, 74 }, { 57, 64, 72, 76 },
        };
        static const double COST[5] = { 2.2, 5.0, 6.0, 4.0, 6.0 };
        int prev[6];
        uint32_t prevLen = 0;
        for (int i = 0; i < 5; ++i) {
            int out[6];
            double cost = 0.0;
            uint32_t n = ano_voice_chord(PCS[i], PCN[i], prev, prevLen, NULL, out, &cost);
            CHECK(n == 4u, "voice_chord voice count");
            bool ok = n == 4u && feq(cost, COST[i]);
            for (uint32_t v = 0; ok && v < n; ++v)
                ok = out[v] == V[i][v];
            if (!ok)
                printf("  voice %d: got %d %d %d %d cost %.17g\n", i,
                       out[0], out[1], out[2], out[3], cost);
            CHECK(ok, "voice_chord voicing + cost");
            memcpy(prev, out, sizeof out);
            prevLen = n;
        }
    }

    // --- chord symbols ---
    {
        AnoScale C = { 0, ANO_MODE_IONIAN };
        struct { AnoChord c; const char *sym; } S[10] = {
            { ano_chord(5, ANO_EXT_7), "V7" },
            { ano_chord(4, 0), "IV" },
            { { 6, 0, 0, ANO_MODE_AEOLIAN, 0, true }, "bVI" },
            { { 2, ANO_EXT_7, 1, ANO_MODE_NONE, 0, true }, "ii65" },
            { { 1, 0, 2, ANO_MODE_NONE, 0, true }, "I64" },
            { ano_chord(7, 0), "vii\xC2\xB0" },
            { ano_chord_applied_dominant(6, true), "V7/vi" },
            { ano_chord(5, ANO_EXT_SUS4), "Vsus4" },
            { ano_chord(1, ANO_EXT_9), "I(add9)" },
            { ano_chord(5, ANO_EXT_7 | ANO_EXT_9), "V9" },
        };
        char buf[32];
        for (int i = 0; i < 10; ++i) {
            ano_chord_symbol(S[i].c, C, buf, sizeof buf);
            if (strcmp(buf, S[i].sym) != 0)
                printf("  sym %d: got '%s' want '%s'\n", i, buf, S[i].sym);
            CHECK(strcmp(buf, S[i].sym) == 0, "chord symbol");
        }
    }

    // --- guide-tone thread ---
    {
        AnoScale C = { 0, ANO_MODE_IONIAN };
        AnoChord prog[7] = {
            ano_chord(1, 0), ano_chord(4, 0), ano_chord(5, ANO_EXT_7),
            ano_chord(6, 0), ano_chord(2, ANO_EXT_7), ano_chord(5, 0), ano_chord(1, 0),
        };
        static const int G[7] = { 4, 0, 11, 0, 0, 11, 7 };
        int prevPc = -1;
        for (int i = 0; i < 7; ++i) {
            prevPc = ano_next_guide(prevPc, prog[i], C);
            CHECK(prevPc == G[i], "guide thread");
        }
    }

    // --- pivots + fifths ---
    {
        AnoScale C = { 0, ANO_MODE_IONIAN };
        AnoPivot p[7];
        uint32_t n = ano_find_pivots(C, (AnoScale){ 7, ANO_MODE_IONIAN }, p);
        static const uint8_t PG[4][2] = { {6,2},{1,4},{3,6},{5,1} };
        CHECK(n == 4u, "pivot count C->G");
        for (uint32_t i = 0; i < n && i < 4u; ++i)
            CHECK(p[i].oldDegree == PG[i][0] && p[i].newDegree == PG[i][1], "pivot order C->G");
        n = ano_find_pivots(C, (AnoScale){ 9, ANO_MODE_AEOLIAN }, p);
        static const uint8_t PA[6][2] = { {2,4},{4,6},{6,1},{1,3},{3,5},{5,7} };
        CHECK(n == 6u, "pivot count C->Am");
        for (uint32_t i = 0; i < n && i < 6u; ++i)
            CHECK(p[i].oldDegree == PA[i][0] && p[i].newDegree == PA[i][1], "pivot order C->Am");
        CHECK(ano_fifths_between(0, 7) == 1 && ano_fifths_between(0, 5) == -1
              && ano_fifths_between(0, 6) == 6 && ano_fifths_between(9, 2) == -1,
              "fifths_between");
    }

    // --- scale mechanics ---
    {
        static const uint8_t DOR[7] = { 0, 2, 3, 5, 7, 9, 10 };
        static const uint8_t LOC[7] = { 0, 1, 3, 5, 6, 8, 10 };
        CHECK(memcmp(ano_mode_intervals(ANO_MODE_DORIAN), DOR, 7) == 0, "dorian intervals");
        CHECK(memcmp(ano_mode_intervals(ANO_MODE_LOCRIAN), LOC, 7) == 0, "locrian intervals");
        CHECK(ano_scale_pitch_at((AnoScale){ 2, ANO_MODE_DORIAN }, 9, 4) == 76, "pitch_at wrap");
        CHECK(ano_scale_pitch_at((AnoScale){ 0, ANO_MODE_IONIAN }, 1, 4) == 60, "pitch_at C4");
        AnoScale C = { 0, ANO_MODE_IONIAN };
        CHECK(ano_snap_to_scale(C, 61) == 62 && ano_snap_to_scale(C, 63) == 64, "snap");
        CHECK(ano_diatonic_shift(C, 60, 3) == 65 && ano_diatonic_shift(C, 61, -2) == 59,
              "diatonic shift");
    }

    if (failures) {
        printf("anotest_music: %d FAILURE(S)\n", failures);
        return 1;
    }
    printf("anotest_music: all passed\n");
    return 0;
}
